const dummy = require("faker");
const replace = require("string-template");
const dateFormat = require("dateformat");
const emailServerID = "bckiwaav";
const emailDomain = "@mailosaur.io";
module.exports = {
  name: {
    first: "SPQA FN " + dummy.name.firstName(),
    last: "SPQA LN " + dummy.name.lastName(),
  },

  type: {
    tier: "one",
  },

  format: {
    date: {
      year: "yyyy",
      month: "mm",
    },
  },

  credential: {
    email: {
      stamp: "SPQA",
      clinic:
        "{placeholder}_clinic_" +
        dummy.random.alphaNumeric(3) +
        "_" +
        dateFormat(new Date(), "mmmddyyyyhhmmssLTT") +
        "." +
        emailServerID +
        emailDomain,
      laboratory:
        "{placeholder}_lab_" +
        dummy.random.alphaNumeric(3) +
        "_" +
        dateFormat(new Date(), "mmmddyyyyhhmmssLTT") +
        "." +
        emailServerID +
        emailDomain,
    },
    password: {
      new: dummy.internet.password(),
      default: "",
    },
    creditCard: {
      number: {
        valid: "4242424242424242",
      },
    },
  },

  axis: {
    x: 100,
    y: -200,
  },

  mailosaur: {
    api: "iIkGqxQsxFzI3G1",
    serverID: "bckiwaav",
  },

  wait: {
    seconds: 5,
  },

  id: {
    clinic: "clinic_" + dummy.random.alphaNumeric(7),
    laboratory: "laboratory_" + dummy.random.alphaNumeric(7),
  },

  schedule: {
    clinic: {
      businessDays: ["monday", "tuesday"],
      businessHours: {
        start: {
          monday: "08:00 AM",
          tuesday: "08:00 AM",
          wednesday: "08:00 AM",
          thursday: "08:00 AM",
          friday: "08:00 AM",
          saturday: "08:00 AM",
        },
        end: {
          monday: "08:00 PM",
          tuesday: "08:00 PM",
          wednesday: "08:00 PM",
          thursday: "08:00 PM",
          friday: "08:00 PM",
          saturday: "08:00 PM",
        },
      },
      phlebotomyServiceDays: ["monday"],
      phlebotomyServiceHours: {
        start: {
          monday: "01:00 PM",
          tuesday: "01:00 PM",
          wednesday: "01:00 PM",
          thursday: "01:00 PM",
          friday: "01:00 PM",
          satuday: "01:00 PM",
        },
        end: {
          monday: "07:30 PM",
          tuesday: "07:30 PM",
          wednesday: "07:30 PM",
          thursday: "07:30 PM",
          friday: "07:30 PM",
          satuday: "07:30 PM",
        },
      },
    },
    laboratory: {
      businessDays: ["monday", "tuesday"],
      businessHours: {
        start: {
          monday: "12:00 AM",
          tuesday: "12:00 AM",
          wednesday: "12:00 AM",
          thursday: "12:00 AM",
          friday: "12:00 AM",
          saturday: "12:00 AM",
        },
        end: {
          monday: "11:30 PM",
          tuesday: "11:30 PM",
          wednesday: "11:30 PM",
          thursday: "11:30 PM",
          friday: "11:30 PM",
          saturday: "11:30 PM",
        },
      },
    },
  },

  addUsers: {
    lab: {
      roles: ["Admin", "Contributor", "IT Admin", "Legal Admin"],
    },
  },

  array: {
    clinicAffiliation: [
      "Hometown Health Care",
      "Hometown Health Services",
      "Cleveland Home Health Network",
    ],
    county: [
      "Callahan County",
      "Jones County",
      "Taylor County",
      "Aguada Municipio",
      "Aguadilla Municipio",
      "Añasco Municipio",
      "Isabela Municipio",
      "Lares Municipio",
      "Moca Municipio",
      "Rincón Municipio",
    ],
    labSpecialtyAndDescription: {
      labFocus: ["Option A", "Option B", "OptionA", "OptionB"],
    },
    msa: [
      "Akron",
      "Albany",
      "Albuquerque",
      "Alexandria",
      "Allentown",
      "Amarillo",
      "Anaheim",
      "Anchorage",
      "Anderson",
      "Ann Arbor",
      "Appleton",
      "Ashland",
      "Arlington",
      "Asheville",
      "Atlanta",
      "Atlantic City",
      "Augusta",
      "Aurora",
      "Austin",
      "Bakersfield",
      "Baltimore",
      "Baton Rouge",
      "Beaumont",
      "Bellevue",
      "Berkeley",
      "Bethlehem",
      "Biloxi",
      "Binghamton",
      "Birmingham",
      "Bloomington",
      "Boardman",
      "Boise City",
      "Bossier City",
      "Boston",
      "Boulder",
      "Bradenton",
      "Bremerton",
      "Brent",
      "Bridgeport",
      "Bristol",
      "Brownsville",
      "Bryan",
      "Buffalo",
      "Cambridge",
      "Camden",
      "Canton",
      "Cape Coral",
      "Carlisle",
      "Carlsbad",
      "Carmel",
      "Cary",
      "Cedar Rapids",
      "Champaign",
      "Chandler",
      "Chapel Hill",
      "Charleston",
      "Charlotte",
      "Charlottesville",
      "Chattanooga",
      "Chicago",
      "Chico",
      "Chula Vista",
      "Cincinnati",
      "Clarksville",
      "Clearfield",
      "Clearwater",
      "Cleveland",
      "College Station",
      "Colorado Springs",
      "Columbia",
      "Columbus",
      "Concord",
      "Conway",
      "Corpus Christi",
      "Council Bluffs",
      "Crestview",
      "Dallas",
      "Davenport",
      "Davidson",
      "Dayton",
      "Daytona Beach",
      "Dearborn",
      "Deltona",
      "Denver",
      "Des Moines",
      "Destin",
      "Detroit",
      "Duluth",
      "Durham",
      "East Hartford",
      "East Lansing",
      "Easton",
      "Edinburg",
      "El Paso",
      "Elgin",
      "Elyria",
      "Erie",
      "Eugene",
      "Evansville",
      "Fargo",
      "Fayette",
      "Fayetteville",
      "Flint",
      "Folsom",
      "Fort Collins",
      "Fort Lauderdale",
      "Fort Myers",
      "Fort Smith",
      "Fort Walton Beach",
      "Fort Wayne",
      "Fort Worth",
      "Franklin",
      "Fresno",
      "Gainesville",
      "Gastonia",
      "Georgetown",
      "Grand Rapids",
      "Greeley",
      "Green Bay",
      "Greensboro",
      "Greenville",
      "Gulfport",
      "Hagerstown",
      "Hammonton",
      "Hanover",
      "Harlingen",
      "Harrisburg",
      "Hartford",
      "Henderson",
      "Hickory",
      "High Point",
      "Hillsboro",
      "Honolulu",
      "Hooversville",
      "Houston",
      "Huntington",
      "Huntsville",
      "Indianapolis",
      "Jackson",
      "Jacksonville",
      "Jefferson",
      "Jersey City",
      "Kalamazoo",
      "Kansas City",
      "Kennewick",
      "Kentwood",
      "Killeen",
      "Kingsport",
      "Kissimmee",
      "Knoxville",
      "Lacey",
      "Lafayette",
      "Lakeland",
      "Lakewood",
      "Lancaster",
      "Lansing",
      "Laredo",
      "Las Vegas",
      "Lenoir",
      "Lexington",
      "Lincoln",
      "Little Rock",
      "Long Beach",
      "Los Angeles",
      "Louisville",
      "Lubbock",
      "Lynchburg",
      "Madison",
      "Manchester",
      "Marco Island",
      "Martinsburg",
      "Massillon",
      "McAllen",
      "Melbourne",
      "Memphis",
      "Merced",
      "Mesa",
      "Metairie",
      "Miami",
      "Middletown",
      "Milford",
      "Milwaukee",
      "Minneapolis",
      "Mishawaka",
      "Mission",
      "Mobile",
      "Modesto",
      "Moline",
      "Montgomery",
      "Morganton",
      "Murfreesboro",
      "Myrtle Beach",
      "Naperville",
      "Naples",
      "Nashua",
      "Nashville",
      "New Braunfels",
      "New Haven",
      "New London",
      "New Orleans",
      "New York",
      "Newark",
      "Newburgh",
      "Newport News",
      "Newton",
      "Norfolk",
      "North Charleston",
      "North Little Rock",
      "North Myrtle Beach",
      "North Port",
      "Norwalk",
      "Norwich",
      "Oakland",
      "Ocala",
      "Ogden",
      "Oklahoma City",
      "Olympia",
      "Omaha",
      "Ontario",
      "Orem",
      "Orlando",
      "Ormond Beach",
      "Oxnard",
      "Palm Bay",
      "Paradise",
      "Paso Robles",
      "Pensacola",
      "Peoria",
      "Petaluma",
      "Philadelphia",
      "Phoenix",
      "Pittsburgh",
      "Pompano Beach",
      "Port Arthur",
      "Port Orchard",
      "Port Saint Lucie",
      "Portage",
      "Portland",
      "Poughkeepsie",
      "Prescott",
      "Prescott Valley",
      "Princeton",
      "Providence",
      "Provo",
      "Raleigh",
      "Reading",
      "Reno",
      "Richland",
      "Richmond",
      "Riverside",
      "Roanoke",
      "Rochester",
      "Rock Island",
      "Rockford",
      "Rogers",
      "Rome",
      "Roseville",
      "Roswell",
      "Round Rock",
      "Sacramento",
      "Saint Louis",
      "Saint Paul",
      "Saint Petersburg",
      "Salem",
      "Salinas",
      "Salisbury",
      "Salt Lake City",
      "San Antonio",
      "San Bernardino",
      "San Diego",
      "San Francisco",
      "San Jose",
      "San Luis Obispo",
      "Sandy Spring",
      "Sanford",
      "Santa Barbara",
      "Santa Clara",
      "Santa Cruz",
      "Santa Maria",
      "Santa Rosa",
      "Sarasota",
      "Savannah",
      "Schenectady",
      "Scranton",
      "Seattle",
      "Shreveport",
      "Silverdale",
      "Sioux Falls",
      "South Bend",
      "South Portland",
      "Spartanburg",
      "Spokane",
      "Springdale",
      "Springfield",
      "Stamford",
      "Stockton",
      "Sugar Land",
      "Sunnyvale",
      "Syracuse",
      "Tacoma",
      "Tallahassee",
      "Tampa",
      "Temple",
      "Thousand Oaks",
      "Titusville",
      "Toledo",
      "Topeka",
      "Towson",
      "Trenton",
      "Troy",
      "Tucson",
      "Tulsa",
      "Tumwater",
      "Tuscaloosa",
      "Tyler",
      "Urbana",
      "Utica",
      "Vallejo",
      "Vancouver",
      "Ventura",
      "Virginia Beach",
      "Visalia",
      "Waco",
      "Warren",
      "Warwick",
      "Washington",
      "Watsonville",
      "Waukesha",
      "West Des Moines",
      "Wichita",
      "Wilkes Barre",
      "Wilmington",
      "Winston",
      "Winter Haven",
      "Woodland",
      "Worcester",
      "Yakima",
      "York",
      "Youngstown",
      "Kettering",
      "Ferry Pass",
      "Cheektowaga",
    ],
  },

  role: {
    clinic: {
      admin: "Admin",
      contributor: "Contributor",
    },
  },

  paymentOfCollections: {
    willYourLabBeResponsibleForPaymentOfCollections: {
      answer: true,
      defaultPaymentOfCollection: 99
    }
  }
};
